# Use an official Python runtime as a parent image
FROM python:3.8

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Expose the port that the app will run on
EXPOSE 8000

# Run Django migrations
RUN python manage.py migrate

# Collect static files
RUN python manage.py collectstatic --noinput

Run python manage.py load_foodtrucks food-truck-data.csv --columns FacilityType LocationDescription Address Status FoodItems Latitude Longitude dayshours Approved ExpirationDate ZipCodes

# Define the command to run your application
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "food_truck_prj.wsgi:application"]
